import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

/**
 * Layout forms the framework for our page layout, including Header,
 * Title, Navigation, Footer.
 * 
 * Populates the main section with children data. To use, wrap page
 * content with <Layout></Layout> tags for each page.
 * 
 * @param {*} props 
 * @returns 
 */
const Layout = (props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <h1 className={styles.title}>
                    Spacetagram
                </h1>   

                {props.children}

            </main>
        </div>
    )
}

export default Layout
